app/main/page.tsx
resolves #5
(member)폴더가 메인폴더를 대체하는 것 같아 메인폴더를 삭제합니다.
=> Chore: 메인 폴더 삭제

app/api/auth/[...nextauth]/route.ts, app/api/auth/withdraw/route.ts, app/components/WithdrawButton.tsx, application/usecase/user/WithdrawUser.ts, domain/repositories/UserRepository.ts, infra/repositories/prisma/PrUserRepository.ts, types/next-auth.d.ts
resolves #24
회원탈퇴 기능 추가(탈퇴 시 회고나 레포는 냅두고 deleted_at만 변경) 일단 기능만 되게 만들고 ui는 추후 확정
토큰에 id추가
=> Feat: 회원탈퇴 기능 추가

app/components/Button.tsx, app/globals.css
resolves #27 
1. 공통 UI로 사용할 수 있는 Button 컴포넌트를 추가했습니다.
2. 버튼은 스타일(type), 사이즈(size), 아이콘, 클릭 이벤트 등 다양한 옵션을 props로 전달받아 재사용이 가능합니다.
3. danger hover 색상으로 --color-error2 (#b83232) 추가했읍니다.
- Button 컴포넌트 구현
- type: "default" | "lined" | "disabled" | "danger"
- size: "regular" | "full"
- label, children, icon, onClick, htmlType props 지원
danger hover 색상으로 --color-error2 (#b83232) 추가 완료
=> Feat: app/components > Button.tsx 컴포넌트 추가

app/(member)/commits/page.tsx, app/(member)/components/PageTab.tsx, app/components/Header.tsx, app/globals.css, app/layout.tsx
resolves #8
헤더와 페이지 탭을 추가하였습니다
페이지 탭 사용 예시
```
<pageTap status="commit"/> // 커밋탭 선택
<pageTap status="pullRequest"/> // PR탭 선택
```
commitsPage에서 date 오류가 있어 살짝 수정했습니다.
=> Feat: 공통 컴포넌트 중 헤더와 페이지탭 추가

.gitignore, app/(member)/components/RepoSelectModal.tsx, app/api/repos/save/route.ts, application/usecase/repo/SaveRepos.ts, application/usecase/repo/dto/SaveReposDto.ts, domain/repositories/RepoRepository.ts, infra/repositories/prisma/PrRepoRepository.ts
resolves #31 
저장소 추가 버튼 누른 후 나오는 모달에서 레포 선택 후 저장소 연동하기 누르면 DB Repo에 해당 정보 저장하는 기능 추가
Repo테이블에 name에 repo id값으로 저장(고유값), repo이름은 변경가능해서 일단 id로 넣어놓음
=> Feat: 저장소 추가 버튼 누른 후 나오는 모달에서 레포 선택 후 저장소 연동하기 누르면 DB Repo에 해당 정보 저장하는 기능 추가

app/(member)/components/RepoSelectModal.tsx, app/api/repos/user/route.ts, application/usecase/repo/FindUserRepos.ts, application/usecase/repo/dto/FindUserReposDto.ts, domain/repositories/RepoRepository.ts, infra/repositories/prisma/PrRepoRepository.ts
resolves #37 
저장소추가 버튼 눌렀을 때 모달에서 이미 저장한 레포들 체크되어 나오는 기능 추가
=> Feat: 저장소추가 버튼 눌렀을 때 모달에서 이미 저장한 레포들 체크되어 나오는 기능 추가

app/(member)/components/SideBar.tsx, app/(member)/layout.tsx, app/(member)/memoirs/components/Filter/CommitPrFilter.tsx, app/(member)/memoirs/page.tsx, package-lock.json, package.json, store/useFilterStore.ts
resolves #36
내 회고록에서 commit이나 pr을 선택하는 필터를 추가하였습니다.
선택을 하면 filters에 commits이나 pullRequests가 boolean값으로 변경되게 작성하였습니다.
layout을 (member)폴더 아래에 추가하였습니다.
=> Feat: 회고록 Commit,Pr 필터 추가

app/(member)/[type]/memoir/page.tsx, app/(member)/commits/[id]/page.tsx, app/(member)/commits/page.tsx, app/(member)/components/PageTab.tsx, app/(member)/components/SideBar.tsx, app/(member)/layout.tsx, app/(member)/memoirs/components/Filter/CommitPrFilter.tsx, app/(member)/memoirs/page.tsx, app/(member)/pull-requests/[id]/page.tsx, app/(member)/pull-requests/page.tsx
resolves #33 
layout.tsx 파일 수정하였습니다.
1. 사이드바와 상단탭을 layout.tsx 에만 추가하여 중첩으로 표시되지 않도록 수정하였읍니다.
2. /memoirs 페이지에 접속하면 commit/pr 필터가 표시되도록 수정하였읍니다.
3. 페이지 url 에 따라 상단 메뉴 탭 하이라이트 표시되도록 수정하였읍니다.
=> 선택한 탭이 하이라이트 처리됩니다.
=> "내 회고록" 탭이 선택된 경우, 좌측에 필터가 추가되고, "내 회고록" 탭이 하이라이트 처리됩니다.
@yoonstar1996 님 [type]/memoir/page.tsx 의 params type 아래 이미지처럼 수정하였읍니다 확인 부탁드립니다.
=> Feat: member/layout.tsx UI 수정 작업

application/usecase/repo/SaveRepos.ts, domain/repositories/RepoRepository.ts, infra/repositories/prisma/PrRepoRepository.ts
…
resolves #40 
저장소추가 버튼 눌렀을 때 모달에서 연동하기 누를 때 이미 체크되어 있던 레포는 추가되지 않고 없어진건 삭제하는 기능 추가
=> Feat: 저장소추가 버튼 눌렀을 때 모달에서 연동하기 누를 때 이미 체크되어 있던 레포는 추가되지 않고 없어진건 삭제하는 기능 추가

app/components/LogoutButton.tsx
=> Feat: 로그아웃 기능 추가

app/(member)/components/SideBar.tsx, app/(member)/components/TimeFilter.tsx, store/useFilterStore.ts
resolves #44
시간별 필터 기능을 추가하였습니다.
useFilterStore에 TimePeriod에 값을 저장하게 추가하였습니다.
option 모달의 경우 커스텀하여 디자인을 변경하였습니다.
=> Feat: Time Period 필터 추가

app/member/components/SideBar.tsx, app/member/memoirs/components/Filter/CommitPrFilter.tsx, app/member/memoirs/components/Filter/TagFilter.tsx, store/useFilterStore.ts
resolves #61
내 회고록에 태그 필터를 추가하였습니다.
필터를 선택하면 useFilterStore에 태그를 스트링 배열로 저장하게 했습니다.
=> Feat: 태그 필터 추가

app/page.tsx
resolves #71 
초기페이지에서 로그인하면 로그인버튼대신 “마이페이지”로 수정
=> Feat: 초기페이지에서 로그인하면 로그인버튼대신 “마이페이지”로 수정

middleware.ts
resolves #82 
로그인 안했을 때, member 페이지 접근 막기
=> Feat: 로그인 안했을 때, member 페이지 접근 막기

app/api/stats/commits/route.ts, app/member/components/SideBar.tsx, app/member/stats/page.tsx, application/usecase/github/FetchCommitStats.ts, application/usecase/github/dto/FetchCommitStatsDto.ts, application/usecase/github/dto/ResponseCommitStatsDto.ts, domain/repositories/StatsRepository.ts, infra/repositories/github/GbStatsRepository.ts, store/repoStore.ts
resolves #84 
통계페이지에서 레포별로 전체커밋 수 보여주는 기능 구현
=> Feat: 통계페이지에서 레포별로 전체커밋 수 보여주는 기능 구현

app/api/stats/lines/route.ts, app/member/stats/page.tsx, application/usecase/github/FetchLinesStats.ts, domain/repositories/StatsRepository.ts, infra/repositories/github/GbStatsRepository.ts
resolves #88
통계페이지에서 레포별로 코드라인 수 보여주는 기능 구현
=> Feat: 통계페이지에서 레포별로 코드라인 수 보여주는 기능 구현

app/api/stats/memoirs/route.ts, app/api/stats/top-active-repos/route.ts, app/api/stats/weekly-commits/route.ts, app/member/components/SideBar.tsx, app/member/stats/components/BottomCard.tsx, app/member/stats/components/ChartSkeleton.tsx, app/member/stats/components/StatsCard.tsx, app/member/stats/components/TopReposSkeleton.tsx, app/member/stats/components/WeeklyCommitChart.tsx, app/member/stats/page.tsx, application/usecase/github/FetchLinesStats.ts, application/usecase/github/FetchTopActiveRepos.ts, application/usecase/github/FetchWeeklyCommits.ts, application/usecase/github/dto/FetchWeeklyCommitsDto.ts, application/usecase/github/dto/ResponseTopActiveReposDto.ts, application/usecase/github/dto/ResponseWeeklyCommitsDto.ts, application/usecase/memoir/FetchMemoirCount.ts, application/usecase/memoir/dto/FetchMemoirCountDto.ts, domain/repositories/MemoirRepository.ts, domain/repositories/StatsRepository.ts, infra/repositories/github/GbStatsRepository.ts, infra/repositories/prisma/PrMemoirRepository.ts, package-lock.json, package.json, store/repoStore.ts
resolves #90 
1. 통계페이지에서 레포별로 작성된 회고록 보여주는 기능 구현
전체커밋, 코드라인수는 소유자명/레포명 만 있으면 됬지만,
회고록은 repoId가 필요
zustand repoStore.ts에서 selectedRepo, setSelectedRepo에 id값도 추가로 넘기도록 수정함
SideBar는 그에 맞게 수정해놨는데 커밋목록페이지에서 수정필요할 수도
2. 통계페이지에서 가장 활발한 저장소 커밋수 기준 보여주는 기능 구현
3. 통계페이지에서 커밋활동 최근7일 보여주는 기능 구현(그래프를 위해 chart.js, react-chartjs-2, chartjs-plugin-datalabels설치)
4. 통계페이지에서 레포별로 전체커밋 수 일주일전과 비교해서 %로 보여주는 기능 구현
%로 보여주는게 맞나 검토 필요 -> 깃고의 경우 7일전 커밋 7, 현재 커밋 85 %로 하면 1114%
5. 통계페이지에서 레포별로 코드라인 수 일주일전과 비교해서 %로 보여주는 기능 구현
코드라인 수는 -가 나올 수 있음(StatsCard 수정함 -일때는 ⬇ 빨간색으로 나오게)
코드라인 수는 주간 단위로 비교가 가능함 -> TimePeriod 적용 불가할 듯
1.
2.
3.
4.
5.
=> Feat: 통계페이지에서 레포별로 작성된 회고록 보여주는 기능 구현 + @

app/api/github/repos/route.ts, app/api/repos/save/route.ts, app/api/repos/user/route.ts, app/api/stats/commits/route.ts, app/api/stats/lines/route.ts, app/api/stats/memoirs/route.ts, app/api/stats/top-active-repos/route.ts, app/api/stats/weekly-commits/route.ts, app/member/stats/components/StatsCard.tsx, app/member/stats/page.tsx, application/usecase/github/FetchCommitStatsUsecase.ts, application/usecase/github/FetchLinesStatsUsecase.ts, application/usecase/github/FetchReposUsecase.ts, application/usecase/github/FetchTopActiveReposUsecase.ts, application/usecase/github/FetchWeeklyCommitsUsecase.ts, application/usecase/memoir/FetchMemoirCountUsecase.ts, application/usecase/repo/FindUserReposUsecase.ts, application/usecase/repo/SaveReposUsecase.ts
resolves #99 
1. 통계페이지에서 일주일전과 비교해서 %로 보여주는 부분 변화량으로 수정
2. usecase파일들에 Usecase 붙이기
=> Feat: 통계페이지에서 일주일전과 비교해서 %로 보여주는 부분 변화량으로 수정 + @

app/api/auth/[...nextauth]/route.ts, app/api/github/commits/route.ts, app/components/Pagination.tsx, app/member/commits/components/CommitCard.tsx, app/member/commits/page.tsx, app/member/layout.tsx, application/usecase/github/FetchCommitListUsecase.ts, application/usecase/github/dto/GithubCommitListDto.ts, domain/repositories/GithubCommitListRepository.ts, infra/repositories/github/GbCommitListRepository.ts, types/next-auth.d.ts
resolves #98 
1. 페이지네이션 컴포넌트 추가하였습니다.
2. commits 목록 페이지에서 작동하도록 코드 수정하였습니다.
3. 세션에 id, githubId 추가되도록 수정하였습니다.
1. 페이지네이션 컴포넌트 추가하였습니다.
2. commits 목록 페이지에서 작동하도록 코드 수정하였습니다.
3. 세션에 id, githubId 추가되도록 수정하였습니다.
=> Feat: 페이지네이션 추가

app/member/components/SideBar.tsx, app/member/components/SideBarRepoSkeleton.tsx, app/member/stats/components/ChartSkeleton.tsx, app/member/stats/components/TopReposSkeleton.tsx, app/member/stats/page.tsx
resolves #106 
1. 통계페이지에서 커밋활동(최근7일), 가장 활발한 저장소(커밋 수 기준) 스켈레톤 안되는 현상 수정
2. 사이드바에서 저장소목록 보이는 곳에도 로딩될 때 스켈레톤 적용
=> Chore: 통계페이지에서 커밋활동(최근7일), 가장 활발한 저장소(커밋 수 기준) 스켈레톤 안되는 현상 수정 + @

app/member/stats/page.tsx, app/page.tsx
resolves #117 
1. 통계페이지에서 스크롤바 안생기도록 수정하기
2. 홈페이지에서 스크롤바 안보이도록 수정하기
3. 홈페이지 SSR로 수정
1.
2.
=> Chore: 통계페이지에서 스크롤바 안생기도록 수정하기 + @

prisma/migrations/20250521052427_edit_memoir_tag_table/migration.sql, prisma/schema.prisma
resolves #130 
Memoir 및 Tag 관련 테이블 속성을 수정합니다.
회고 작성 기능 구현을 위해 Memoir 및 Tag 테이블 속성 수정하였읍니다.
=> Feat: DB 업데이트

prisma/schema.prisma
resolves #132 
prisma db pull 했읍니다.
=> Chore: schema.prisma DB pull

infra/repositories/github/GbStatsRepository.ts
resolves #139 
통계페이지에서 커밋 하나도 없는 레포 통계 안나타나는 오류 해결하기
=> fix: 통계페이지에서 커밋 하나도 없는 레포 통계 안나타나는 오류 해결하기

app/api/memoir/[id]/route.ts, app/components/Header.tsx, app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/CreateMemoir/EditorForm.tsx, app/member/components/CreateMemoir/EditorFormReadOnly.tsx, app/member/components/CreateMemoir/plate-editor/ui/plate-editor.tsx, app/member/layout.tsx, app/member/memoirs/[id]/page.tsx, app/member/memoirs/commit/[id]/page.tsx, app/member/memoirs/components/Detail/DetailMemoir.tsx, app/member/memoirs/components/Detail/DetailMemoirLayout.tsx, app/member/memoirs/components/MemoirCard.tsx, app/member/memoirs/pull-request/[id]/page.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, application/usecase/memoir/EditMemoirUsecase.ts, application/usecase/memoir/GetMemoirUsecase.ts, application/usecase/memoir/dto/EditMemoirDto.ts, application/usecase/memoir/dto/GetMemoirDto.ts, constants/url.ts, domain/repositories/MemoirRepository.ts, hooks/useCreateEditor.ts, hooks/useMemoirForm.ts, infra/repositories/prisma/PrMemoirRepository.ts, prisma/schema.prisma, types/memoir/Memoir.ts
resolves #128 
회고록 조회 가능(회고록 목록에서 클릭 시, memoirId로 조회)
회고록 수정 가능
=> Feat: 회고록 조회, 수정 작업

app/member/memoirs/components/MemoirSkeleton.tsx, app/member/memoirs/page.tsx
resolves #143 
회고목록페이지에서 로딩중일때 스켈레톤 적용하기
=> Feat: 회고목록페이지에서 로딩중일때 스켈레톤 적용하기

app/member/components/PageTab.tsx, app/member/components/SideBar.tsx, app/member/layout.tsx, app/member/memoirs/components/Filter/SearchFilter.tsx
=> Feat: 회고록 검색창 ui 추가

app/member/memoirs/components/MemoirCard.tsx
resolves #150 
회고목록페이지에서 회고의 내용 json 잘 처리하고 디자인 조정하기
=> Feat: 회고목록페이지에서 회고의 내용 json 잘 처리하고 디자인 조정하기

app/member/components/SideBar.tsx, store/repoStore.ts
resolves #153 
repoStore에 dbid도 추가하고 값 나오도록 구현
=> Feat: repoStore에 dbid도 추가하고 값 나오도록 구현

app/api/memoirs/tags/route.ts, app/member/components/SideBar.tsx, application/usecase/memoir/GetMemoirTagsUsecase.ts, domain/repositories/MemoirRepository.ts, infra/repositories/prisma/PrMemoirRepository.ts
resolves #170 
회고목록페이지에서 사이드바에 레포별로 내가 작성한 회고의 태그들 나오는 기능 구현하기
=> Feat: 회고목록페이지에서 사이드바에 레포별로 내가 작성한 회고의 태그들 나오는 기능 구현하기

app/api/memoirs/route.ts, app/member/memoirs/components/Filter/CommitPrFilter.tsx, app/member/memoirs/page.tsx, application/usecase/memoir/GetMyMemoirsUsecase.ts, domain/repositories/MemoirRepository.ts, infra/repositories/prisma/PrMemoirRepository.ts
resolves #174 
회고목록페이지에서 사이드바에 태그 누르면 해당 태그를 가진 회고목록 나오는 기능 구현하기
=> Feat: 회고목록페이지에서 사이드바에 태그 누르면 해당 태그를 가진 회고목록 나오는 기능 구현하기

app/api/github/commits/detail/route.ts, app/api/memoirs/route.ts, app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/CreateMemoir/FileNodeComponent.tsx, app/member/memoirs/components/Filter/CommitPrFilter.tsx, app/member/memoirs/page.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, application/usecase/github/FetchCommitDetailUsecase.ts, application/usecase/github/dto/GithubCommitDetailDto.ts, application/usecase/github/dto/GithubCommitListDto.ts, application/usecase/memoir/GetMyMemoirsUsecase.ts, domain/entities/GithubCommitDetail.ts, domain/repositories/GithubCommitDetailRepository.ts, domain/repositories/MemoirRepository.ts, infra/repositories/github/GbCommitDetailRepository.ts, infra/repositories/prisma/PrMemoirRepository.ts
resolves #158 
현재 회고 작성 페이지 내에서
1. 커밋 회고 작성 페이지 접속 시 커밋 상세 내역 조회
2. PR 회고 작성 페이지 접속 시 PR 에 해당하는 커밋 목록 조회
=> Feat: 회고 작성 페이지에서 데이터 호출 완료

app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/CreateMemoir/AiSummary.tsx, app/member/layout.tsx, constants/aiPrompt.ts, hooks/useMemoirForm.ts, store/AiSummaryStore.ts
resolves #182 
사이드바 UX 개선 작업을 진행하였읍니다.
1. 사이드바 좌측 고정으로 수정하였읍니다.
2. 사이드바가 길어지는 경우 스크롤이 생깁니다.
=> Feat: 사이드바 UX 개선 작업

app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/CreateMemoir/AiSummary.tsx, hooks/useSimplifyCommitData.ts
resolves #186
AI 요약 기능 실제 데이터 적용되게 연결하였습니다.
=> Feat: AI 요약 실제 데이터 연결

app/member/memoirs/page.tsx
resolves #195 
회고목록페이지에서 이미 조회했을때 10분 이내로 다시 조회하면 다시 조회하지 않고 아까 조회했던 정보로 보여주는 기능 구현하기
=> Feat: 회고목록페이지에서 이미 조회했을때 10분 이내로 다시 조회하면 다시 조회하지 않고 아까 조회했던 정보로 보여주는 기능 구현하기

app/member/stats/page.tsx
resolves #201 
통계페이지에서 회원탈퇴 누르면 나오는 모달 위에 그래프가 나타나는 현상 수정
=> Fix: 통계페이지에서 회원탈퇴 누르면 나오는 모달 위에 그래프가 나타나는 현상 수정

app/member/components/CreateMemoir/AiSummary.tsx, app/member/components/CreateMemoir/PullRequestAiSummary.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, constants/aiPullRequestPrompt.ts, hooks/useSimplifyPullRequestData.ts
resolves #190
pull request에 대한 ai 요약기능을 추가했습니다.
개발 흐름과 커밋 메세지를 정리하도록 기능을 만들었습니다.
=> PR AI 요약 기능 추가

app/member/stats/page.tsx
resolves #208 
통계페이지에서 통계 불러오는 중에 레포 바꾸면 통계 이상해지는 현상 수정
=> Fix: 통계페이지에서 통계 불러오는 중에 레포 바꾸면 통계 이상해지는 현상 수정

app/member/memoirs/components/Detail/CommitDetailMemoir.tsx, app/member/memoirs/components/Detail/PullRequestDetailMemoir.tsx, app/member/memoirs/components/ViewSummary.tsx
resolves #206
회고록 상세 페이지에서 AI 요약 상세보기 추가하였습니다.
요약이 없으면 생성된 요약이 없다고 뜨게하였습니다.
=> Feat: 회고록 상세 페이지에서 AI 요약 보기 추가

app/member/stats/page.tsx
resolves #215 
통계페이지에서 커밋활동(최근7일) 에 그래프 나오기 전에 커밋정보없음 나오는 부분 ui수정
=> Chore: 통계페이지에서 커밋활동(최근7일) 에 그래프 나오기 전에 커밋정보없음 나오는 부분 ui수정

app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/CreateMemoir/CreateEditorForm.tsx, app/member/components/CreateMemoir/CreateMemoirLayout.tsx, app/member/components/CreateMemoir/plate-editor/ui/plate-editor.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx
resolves #203
회고록 작성 시, 에디터에 스크롤 사라지는 버그 수정했습니다.
=> Fix: 회고록 작성 시, 에디터 영역 스크롤 생성

app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/components/Loading.tsx, app/member/memoirs/components/Detail/CommitDetailMemoir.tsx, app/member/memoirs/components/Detail/PullRequestDetailMemoir.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx
resolves #222
회고록 작성, 조회 페이지 접근 시 로딩 페이지 적용했습니다.
로딩 페이지가 화면 전체 사이즈에 맞도록 조정했습니다.
=> Feat: 회고록 작성, 조회 페이지 접근 시 로딩 페이지 적용

prisma/migrations/20250526051136_user_add_is_default_only/migration.sql, prisma/schema.prisma
resolves #233 
Schema.prisma 의 User 테이블에 isDefaultOnly 속성 추가하였읍니다.
default 값은 true 로 되어 있읍니다.
Schema.prisma 의 User 테이블에 isDefaultOnly 속성 추가하였읍니다.
default 값은 true 로 되어 있읍니다.
=> Feat: Prisma DB isDefaultOnly 속성 추가

infra/repositories/github/GbCommitListRepository.ts
resolves #226 
커밋 목록 불러오는 코드에서 분기처리를 추가하였읍니다.
GbCommitListRepository 에 isDefaultOnly 에 따른 분기처리를 추가하였습니다.
isDefaultOnly === true 면 default 브랜치만 조회합니다
false 인 경우, 전체 작업중인 브랜치를 조회합니다.
실제 표시 UI(default 브랜치만 표시 )
실제 표시 UI(전체 브랜치 표시)
=> Feat: 커밋 목록 불러오기 분기 처리 추가

app/api/auth/join/route.ts, app/api/auth/withdraw/route.ts, app/api/settings/commits/route.ts, app/components/WithdrawButton.tsx, app/member/components/AlertDialog.tsx, app/member/components/SideBar.tsx, app/member/settings/page.tsx, application/usecase/user/CommitSettingUserUsecase.ts, application/usecase/user/GetCommitSettingUsecase.ts, application/usecase/user/JoinUserUsecase.ts, application/usecase/user/WithdrawUserUsecase.ts, application/usecase/user/dto/JoinUserDto.ts, domain/repositories/UserRepository.ts, infra/repositories/prisma/PrUserRepository.ts
resolves #242 
1. 설정에 커밋 가져오기 설정 수정 후 저장하면 DB에 반영되는 기능 구현
2. 설정 저장 후 알림창 커스텀
3. 설정페이지에 접속 시 DB에서 커밋가져오기설정 가져와서 보여주는 기능 구현
4. 설정페이지에 접속 시 모든 브랜치여도 잠깐 기본브랜치가 선택됬다가 바뀌는 현상 수정
5. 설정에 탈퇴하기 동작하게 하기 및 통계 탈퇴하기 버튼 제거
6. joinUser, WithdrawUser 파일명 뒤에 Usecase붙이기
=> Feat: 설정에 커밋가져오기 불러오기/수정 기능 추가

app/components/Header.tsx, app/member/memoirs/components/Detail/CommitDetailMemoir.tsx
resolves #248 
헤더 컴포넌트 및 커밋 회고 상세 페이지 UI 일부 수정하였읍니다
1. 페이지에 따라 헤더 컴포넌트의 레이아웃이 변경됩니다.
2. 커밋 회고 상세 페이지의 커밋 메시지 영역에 음영 추가했읍니다.
=> Style: Header 컴포넌트 레이아웃 조정

app/member/commits/page.tsx
resolves #250 
커밋 페이지에서 캐시 기능 추가하였읍니다.
=> Feat: 커밋 페이지 캐시 기능 추가

app/member/pull-requests/components/PrCard.tsx, app/member/pull-requests/page.tsx
resolves #230 
PR 페이지 캐시 기능 추가하였읍니다.
1. PR 목록 페이지 캐시 기능 추가
2. PR 카드 커밋 목록 캐시 기능 추가
=> Feat: PR 페이지 캐시 기능 추가

app/member/memoirs/components/Filter/TagFilter.tsx, app/member/memoirs/components/MemoirCard.tsx, app/member/memoirs/components/ViewSummary.tsx
=> Release: v 1.1.0 배포

app/member/components/CreateMemoir/CreateEditorForm.tsx, app/member/components/CreateMemoir/EditEditorForm.tsx
=> Fix: MacOS 한글 태그 마지막 자 추가 이슈 수정

app/globals.css, app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/memoirs/components/Detail/CommitDetailMemoir.tsx, app/member/memoirs/components/Detail/PullRequestDetailMemoir.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, package-lock.json, package.json
resolves #288
회고록 작성 및 조회 페이지 resize 기능 추가
=> Feat: 회고록 작성 및 조회 페이지 resize 기능 추가

app/member/commits/page.tsx, infra/repositories/github/GbCommitListRepository.ts
resolves #291 
커밋 목록 조회 시 발생 오류 수정하였읍니다.
1. 최초 커밋 목록 조회 시 렌더링 오류 해결하였읍니다
2. 커밋이 없는 저장소를 선택한 경우 500 에러가 발생했읍니다. 해당 문제 해결했습니다. (이 부분은 dev 브랜치와 비교하면 좋을 것 같읍니다)
=> Fix: 서버에서 배포 서버에서 커밋 목록 접속 시 목록 조회 불가 현상 수정

app/member/components/RepoSelectModal.tsx, app/member/components/SideBar.tsx
resolves #296 
1. 저장소 추가할때 정렬기준 최신 변경순으로 수정
2. 사이드바에서 저장소 정렬기준 저장소에 추가된 과거순으로 수정
=> Chore: 저장소 추가할때 정렬기준, 사이드바에서 저장소 정렬기준 추가

app/api/auth/authOptions.ts, app/member/memoirs/components/Filter/SearchFilter.tsx, app/page.tsx
resolves #305 
1. 회고록페이지에서 검색기능 초기화버튼 호버시 커서로 수정
2. 로그인할때 받는 깃허브 권한 수정
=> Chore: 회고록페이지에서 검색기능 초기화버튼 호버시 커서로 수정 + @

app/member/components/CreateMemoir/AiSummary.tsx, app/member/components/CreateMemoir/PullRequestAiSummary.tsx, app/member/memoirs/components/ViewSummary.tsx
resolves #309
ai 요약을 복사해주는 기능을 넣어 회고록 작성에 보조해주도록 기능을 추가했습니다.
=> Feat: ai 요약 복사 기능 추가

app/member/components/CreateMemoir/AiSummary.tsx, app/member/components/CreateMemoir/CreateEditorForm.tsx, app/member/components/CreateMemoir/EditEditorForm.tsx, app/member/components/CreateMemoir/PullRequestAiSummary.tsx
resolves #313
Copy 이모티콘을 import 안해오는 오류 수정
=> Fix: 루시드 이모티콘 import 안해오는 오류 수정

prisma/migrations/20250602024059_memoir_add_source_title/migration.sql, prisma/schema.prisma
resolves #319 
schema.prisma > Memoir 테이블에 sourceTitle 속성 추가하였읍니다.
schema.prisma > Memoir 테이블에 sourceTitle 속성 추가하였읍니다.
기존의 회고는 sourceTitle 이 "Commit 또는 PR 임시제목" 으로 추가하였읍니다
npx prisma generate 필수입니다
=> Feat: Schema.prisma 에 회고록 source_title 속성 추가

app/member/memoirs/components/MemoirCard.tsx, application/usecase/memoir/dto/MemoirListDto.ts
resolves #321 
회고록목록페이지에서 레포이름대신 커밋이나 PR제목 보여주도록 수정
=> Feat: 회고록목록페이지에서 레포이름대신 커밋이나 PR제목 보여주도록 수정

app/member/memoirs/components/MemoirCard.tsx
resolves #324 
회고록목록페이지에서 커밋이나 PR제목 보여줄때 조건에 맞는 아이콘으로 보여주도록 수정
=> Chore: 회고록목록페이지에서 커밋이나 PR제목 보여줄때 조건에 맞는 아이콘으로 보여주도록 수정

app/member/commits/[sha]/memoir/components/CommitMemoir.tsx, app/member/commits/components/CommitCard.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, app/member/pull-requests/components/PrCard.tsx, store/sourceTitleStore.ts
resolves #323
커밋 회고 작성 버튼 또는 PR 회고 작성 버튼 선택 시 PR 타이틀 전역 상태에 저장
커밋 회고 작성 버튼 또는 PR 회고 작성 버튼 선택 시 PR 타이틀 전역 상태에 저장
=> Feat: PR 회고 카드 선택 시 PR 타이틀 전역 상태에 저장

app/member/components/RepoSelectModal.tsx, application/usecase/repo/SaveReposUsecase.ts, domain/repositories/RepoRepository.ts, infra/repositories/prisma/PrRepoRepository.ts
resolves #340 
레포에 회고를 작성한 후 회원탈퇴를 하고 재가입 후 해당 레포 추가 후 해제할때 작성한 회고가 없어도 작성한 회고가 있다고 나타나는 현상 수정
=> Fix: 레포에 회고를 작성한 후 회원탈퇴를 하고 재가입 후 해당 레포 추가 후 해제할때 작성한 회고가 없어도 작성한 회고가 있다고 나타나는 현상 수정

app/member/components/RepoSelectModal.tsx
=> Chore: 저장소추가 모달 날짜형식 수정

app/member/memoirs/page.tsx
resolves #356 
저장소 연동 없는 경우, 내 회고록 빈 목록이 표시되도록 수정
저장소 연동 없는 경우, 내 회고록 빈 목록이 표시되도록 수정했읍니다.
=> Fix: 저장소 연동 없는 경우, 내 회고록 빈 목록 표시

app/member/components/CreateMemoir/plate-editor/ui/export-toolbar-button.tsx
resolves #363 
theme값 없을 시, export할 때, 기본값 흰색으로 변경했습니다.
=> Fix: theme값 없을 시, export 할 경우 기본값 흰색으로 변경

app/member/components/RepoSelectModal.tsx
resolves #366 
저장소 모달 수정(체크된 저장소가 처음에 맨위로 나오게 수정)
=> Feat: 저장소 모달 수정(체크된 저장소가 처음에 맨위로 나오게 수정)

app/api/github/pull-requests/commits/detail/route.ts, app/api/memoirs/[id]/route.ts, app/api/upload/route.ts, app/member/commits/components/CommitCard.tsx, app/member/commits/page.tsx, app/member/components/CreateMemoir/plate-editor/ui/button.tsx, app/member/components/CreateMemoir/plate-editor/ui/export-toolbar-button.tsx, app/member/components/CreateMemoir/plate-editor/ui/media-popover.tsx, app/member/components/RepoSelectModal.tsx, app/member/memoirs/page.tsx, app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx, app/member/pull-requests/components/PrCard.tsx, application/usecase/github/FetchPrCommitDetailUsecase.ts, application/usecase/github/dto/GithubPrCommitDetailDto.ts, application/usecase/memoir/DeleteMemoirUsecase.ts, domain/entities/GithubPrCommitDetail.ts, domain/repositories/GithubPrCommitDetailRepository.ts, domain/repositories/MemoirRepository.ts, infra/repositories/github/GbCommitDetailRepository.ts, infra/repositories/github/GbPrCommitDetailRepository.ts, infra/repositories/github/GbPrCommitListRepository.ts, infra/repositories/prisma/PrMemoirRepository.ts, lib/plate-utils.ts, lib/s3-client.ts
=> Release v 1.1.4 (main -> dev merge)

app/(anon)/demo/page.tsx, app/components/Button.tsx, app/member/components/CreateMemoir/DemoEditorForm.tsx, app/member/components/CreateMemoir/plate-editor/ui/media-placeholder-element.tsx, app/page.tsx, constants/demo.ts, hooks/useS3Upload.ts
resolves #373 
랜딩 페이지의 로그인 버튼 -> 새로운 탭에서 데모 페이지 열리는 버튼
const 폴더에 데모 페이지에서 보여줄 파일, 코드 변경 내역 추가
데모 페이지에서 이미지 업로드 시, aws s3 스토리지에 업로드 X
=> Feat: 데모 페이지 생성

app/member/commits/page.tsx, app/member/pull-requests/page.tsx, store/useRepoStore.ts
resolves #377 
1. useRepoStore 에 hydration 관련 상태 추가했읍니다.
2. 커밋과 PR 을 fetch 하는 useEffect 부분 수정하였읍니다.
현재 배포 서버에서 커밋 페이지와 PR 페이지에서 새로고침을 하는 경우, 목록이 불러와지지 않는 현상이 발생했읍니다.
이는 새로고침 시 전역 상태에 저장되어 있는 저장소 값을 획득하지 않은 상태에서 fetch 를 실행하는 것으로 추측됩니다.
따라서 fetch 하기 전에 hydration 상태와 저장소 상태를 사용하여 선택된 값이 없는 경우, 실행을 중지하도록 수정함으로써 해결할 수 있을 것 같읍니다.
이를 위해
1. useRepoStore 에 hydration 관련 상태를 추가했읍니다.
2. 커밋과 PR 목록을 조회하는 useEffect 에 해당 상태가 없는 경우 실행을 멈추도록 수정했읍니다.
=> Fix: 새로고침 시 fetch 오류 수정

app/member/components/AlertDialog.tsx, app/member/components/RepoSelectModal.tsx
resolves #379 
1. 저장소 추가 모달에서 esc 눌러도 모달 닫히는 기능 추가
2. Alert 엔터 누르면 확인 버튼 눌리는 기능 추가
=> Feat: 모달창 키 이벤트 추가

public/googlefb1e0c2a7945e170.html
resolves #381 
소유권 확인을 위한 public > googlefb1e0c2a7945e170.html 파일 추가
기존에 속성을 추가할 때 프로토콜과 관계없이 도메인을 속성으로 등록했읍니다.
이는 구글봇이 http, https 인 모든 URL 에 대한 크롤링을 진행하는 방식으로 색인이 진행됩니다.
하지만 현재 http 링크 접속 시 자동으로 https 링크로 리디렉션 되도록 설정해놓았기 때문에 http 로 시작하는 URL 에 대한 색인이 생성되지 않은 것으로 확인됩니다.
이에 따라 프로토콜을 사용하는 URL 로 새로운 속성을 추가할 예정입니다.
https://git-go.co.kr 의 소유권을 확인하기 위해 html 파일을 추가하였읍니다.
=> Fix: 소유권 확인을 위한 html 파일 추가

app/components/ScrollControls.tsx, app/page.tsx
resolves #375
랜딩 페이지 모바일 버전 추가
모바일 버전에서는 feature 설명을 하나의 섹터로 구분 해놨습니다.
=> Feat: 랜딩 페이지 모바일 버전 추가

app/api/login-record/auto/route.ts, app/components/AutoLoginRecord.tsx, app/components/Providers.tsx, app/layout.tsx, app/member/stats/page.tsx, application/usecase/login-record/AutoLoginRecordUsecase.ts, application/usecase/login-record/dto/AutoLoginRecordDto.ts, domain/repositories/LoginRecordRepository.ts, infra/repositories/prisma/PrLoginRecordRepository.ts, package-lock.json, package.json
resolves #393 
사용자가 하루 이상 로그아웃안하고 사용할때에도 출석남기도록 하는 기능 구현
통계페이지 캐싱 기능 고도화(tanstack-query 사용)
=> Feat: 사용자가 하루 이상 로그아웃안하고 사용할때에도 출석남기도록 하는 기능 구현 + @
